//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:2.0.50727.4927
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class protocol {
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("message")]
    public protocolMessage[] message;
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class protocolMessage {
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("error", typeof(protocolMessageError))]
    [System.Xml.Serialization.XmlElementAttribute("gameId", typeof(protocolMessageGameId))]
    [System.Xml.Serialization.XmlElementAttribute("gameMasterLogin", typeof(protocolMessageGameMasterLogin))]
    [System.Xml.Serialization.XmlElementAttribute("gameOver", typeof(protocolMessageGameOver))]
    [System.Xml.Serialization.XmlElementAttribute("gameState", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("move", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("nextPlayer", typeof(protocolMessageNextPlayer))]
    [System.Xml.Serialization.XmlElementAttribute("player", typeof(protocolMessagePlayer))]
    [System.Xml.Serialization.XmlElementAttribute("playerLogin", typeof(protocolMessagePlayerLogin))]
    [System.Xml.Serialization.XmlElementAttribute("response", typeof(protocolMessageResponse))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type;
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class protocolMessageError {
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id;
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class protocolMessageGameId {
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id;
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class protocolMessageGameMasterLogin {
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string gameType;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int playersMin;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int playersMax;
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class protocolMessageGameOver {
    
    /// <uwagi/>
    public protocolMessageGameOverPlayer player;
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class protocolMessageGameOverPlayer {
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nick;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string result;
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class protocolMessageNextPlayer {
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nick;
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class protocolMessagePlayer {
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nick;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string won;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lost;
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class protocolMessagePlayerLogin {
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nick;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string gameType;
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class protocolMessageResponse {
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string accept;
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <uwagi/>
    error,
    
    /// <uwagi/>
    gameId,
    
    /// <uwagi/>
    gameMasterLogin,
    
    /// <uwagi/>
    gameOver,
    
    /// <uwagi/>
    gameState,
    
    /// <uwagi/>
    move,
    
    /// <uwagi/>
    nextPlayer,
    
    /// <uwagi/>
    player,
    
    /// <uwagi/>
    playerLogin,
    
    /// <uwagi/>
    response,
}
